app:
    resource: '@AppBundle/Controller/'
    type: annotation

user:
    resource: '@AppBundle/Controller/UserController.php'
    type: annotation
    prefix: user

admin:
    resource: '@AppBundle/Controller/AdminController.php'
    type: annotation
    prefix: admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
